### ISSUE TITLE
SPIR-V Support

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#383]
This is a tracking issue for tracking what rust-gpu can produce in terms of SPIR-V assembly.

#### Emoji Legend
- 🛑 — Missing
- ⚠️ — Incomplete
- ✅ — Complete

## Execution Models ⚠️

<details><summary>Details</summary>
<p>

- [x] Vertex
- [ ] Tessellation Control
- [ ] Tessellation Evaluation
- [x] Geometry
- [x] Fragment
- [ ] GLCompute
- [x] Kernel (Compute)
- [ ] Task
- [ ] Mesh
- [ ] Ray Generation
- [ ] Ray Intersection
- [ ] Ray Any-hit
- [ ] Ray Closest-hit
- [ ] Ray Miss
- [ ] Ray Callable

</p>
</details>

## Addressing Model ⚠️

<details><summary>Details</summary>
<p>

- [x] Logical
- [ ] Physical32
- [ ] Physical64
- [ ] PhysicalStorageBuffer64
- [ ] PhysicalStorageBuffer64EXT

</p>
</details>

## Memory Model ⚠️

<details><summary>Details</summary>
<p>

- [x] Simple
- [x] GLSL450
- [ ] OpenCL
- [x] Vulkan

</p>
</details>

## Execution Modes 🛑

<details><summary>Details</summary>

### All models 🛑
<details><summary>Details</summary>
<p>

- [ ] Initializer
- [ ] Finalizer
- [ ] SubgroupSize
- [ ] SubgroupsPerWorkgroup
- [ ] SubgroupsPerWorkgroupId
- [ ] PostDepthCoverage
- [ ] DenormPreserve
- [ ] DenormFlushToZero
- [ ] SignedZeroInfNanPreserve
- [ ] RoundingModeRTE
- [ ] RoundingModeRTZ

</p>
</details>

### Kernel 🛑
<details><summary>Details</summary>
<p>

- [ ] LocalSizeHint
- [ ] LocalSizeHintId
- [ ] VecTypeHint
- [ ] ContractionOff
- [ ] MaxWorkgroupSizeINTEL
- [ ] MaxWorkDimINTEL
- [ ] NoGlobalOffsetINTEL
- [ ] NumSIMDWorkitemsINTEL

</p>
</details>

### Kernel & GLCompute 🛑
<details><summary>Details</summary>
<p>

- [ ] LocalSize
- [ ] LocalSizeId
- [ ] ComputeDerivativeGroupLinearNV
- [ ] ComputeDerivativeGroupQuadsNV

</p>
</details>

### Geometry 🛑
<details><summary>Details</summary>
<p>

- [ ] Invocations
- [ ] InputPoints
- [ ] InputLines
- [ ] InputLinesAdjacency
- [ ] InputTrianglesAdjacency

</p>
</details>

### Geometry & Tessellation 🛑
<details><summary>Details</summary>
<p>

- [ ] Triangles
- [ ] OutputVertices

</p>
</details>

### Fragment 🛑
<details><summary>Details</summary>
<p>

- [ ] PixelCenterInteger
- [ ] OriginUpperLeft
- [ ] OriginLowerLeft
- [ ] EarlyFragmentTests
- [ ] DepthReplacing
- [ ] DepthGreater
- [ ] DepthLess
- [ ] DepthUnchanged
- [ ] OutputPoints
- [ ] OutputLineStrip
- [ ] OutputTriangleStrip
- [ ] PixelInterlockOrderedEXT
- [ ] PixelInterlockUnorderedEXT
- [ ] SampleInterlockOrderedEXT
- [ ] SampleInterlockUnorderedEXT
- [ ] ShadingRateInterlockOrderedEXT
- [ ] ShadingRateInterlockUnorderedEXT

</p>
</details>

### Task & Mesh 🛑

<details><summary>Details</summary>
<p>

- [ ] OutputLinesNV
- [ ] OutputTrianglesNV
- [ ] OutputPrimitivesNV

</p>
</details>

### Tessellation 🛑
<details><summary>Details</summary>
<p>

- [ ] SpacingEqual
- [ ] SpacingFractionalEven
- [ ] SpacingFractionalOdd
- [ ] VertexOrderCw
- [ ] VertexOrderCcw
- [ ] PointMode
- [ ] Quads
- [ ] Isolines

</p>
</details>

### Vertex 🛑
- [ ] Xfb

</details>

## Storage Classes ⚠️
<details><summary>Details</summary>
<p>

- [x] UniformConstant
- [x] Input
- [x] Uniform
- [x] Output
- [x] Workgroup
- [x] CrossWorkgroup
- [x] Private
- [x] Function
- [x] Generic
- [x] PushConstant
- [x] AtomicCounter
- [x] Image
- [x] StorageBuffer
- [x] CallableDataKHR
- [x] IncomingCallableDataKHR
- [x] RayPayloadKHR
- [x] HitAttributeKHR
- [x] IncomingRayPayloadKHR
- [x] ShaderRecordBufferKHR
- [x] PhysicalStorageBuffer
- [ ] PhysicalStorageBufferEXT
- [ ] CodeSectionINTEL

</p>
</details>

## Image ⚠️
<details><summary>Details</summary>
<p>

- [x] OpSampledImage
- [x] OpImageSampleImplicitLod
- [ ] OpImageSampleExplicitLod
- [ ] OpImageSampleDrefImplicitLod
- [ ] OpImageSampleDrefExplicitLod
- [ ] OpImageSampleProjImplicitLod
- [ ] OpImageSampleProjExplicitLod
- [ ] OpImageSampleProjDrefImplicitLod
- [ ] OpImageSampleProjDrefExplicitLod
- [ ] OpImageFetch
- [ ] OpImageGather
- [ ] OpImageDrefGather
- [ ] OpImageRead
- [ ] OpImageWrite
- [ ] OpImage
- [ ] OpImageQueryFormat
- [ ] OpImageQueryOrder
- [ ] OpImageQuerySizeLod
- [ ] OpImageQuerySize
- [ ] OpImageQueryLod
- [ ] OpImageQueryLevels
- [ ] OpImageQuerySamples
- [ ] OpImageSparseSampleImplicitLod
- [ ] OpImageSparseSampleExplicitLod
- [ ] OpImageSparseSampleDrefImplicitLod
- [ ] OpImageSparseSampleDrefExplicitLod
- [ ] OpImageSparseFetch
- [ ] OpImageSparseGather
- [ ] OpImageSparseDrefGather
- [ ] OpImageSparseTexelsResident
- [ ] OpImageSparseRead
- [ ] OpImageSampleFootprintNV

</p>
</details>

## Conversions 🛑
<details><summary>Details</summary>
<p>

- [ ] Float <-> unsigned integer
- [ ] Float <-> signed integer
- [ ] OpUconvert
- [ ] OpSConvert
- [ ] OpFConvert
- [ ] OpQuantizeToF16
- [ ] OpConvertPtrToU
- [ ] OpSatConvertSToU
- [ ] OpSatConvertUToS
- [ ] OpConvertUToPtr
- [ ] OpPtrCastToGeneric
- [ ] OpGenericCastToPtr
- [ ] OpGenericCastToPtrExplicit
- [ ] OpBitcast

</p>
</details>

## Composite 🛑
<details><summary>Details</summary>
<p>

- [ ] OpVectorExtractDynamic
- [ ] OpVectorInsertDynamic
- [ ] OpVectorShuffle
- [ ] OpCompositeConstruct
- [ ] OpCompositeExtract
- [ ] OpCompositeInsert
- [ ] OpCopyObject
- [ ] OpTranspose
- [ ] OpCopyLogical

</p>
</details>

## Arithmetic 🛑
<details><summary>Details</summary>
<p>

- [ ] OpSNegate
- [ ] OpFNegate
- [ ] OpIAdd
- [ ] OpFAdd
- [ ] OpISub
- [ ] OpFSub
- [ ] OpIMul
- [ ] OpFMul
- [ ] OpUDiv
- [ ] OpSDiv
- [ ] OpFDiv
- [ ] OpUMod
- [ ] OpSRem
- [ ] OpSMod
- [ ] OpFRem
- [ ] OpFMod
- [ ] OpVectorTimesScalar
- [ ] OpMatrixTimesScalar
- [ ] OpVectorTimesMatrix
- [ ] OpMatrixTimesVector
- [ ] OpMatrixTimesMatrix
- [ ] OpOuterProduct
- [ ] OpDot
- [ ] OpIAddCarry
- [ ] OpISubBorrow
- [ ] OpUMulExtended
- [ ] OpSMulExtended

</p>
</details>

## Bit 🛑
<details><summary>Details</summary>
<p>

- [ ] OpShiftRightLogical
- [ ] OpShiftRightArithmetic
- [ ] OpShiftLeftLogical
- [ ] OpBitwiseOr
- [ ] OpBitwiseXor
- [ ] OpBitwiseAnd
- [ ] OpNot
- [ ] OpBitFieldInsert
- [ ] OpBitFieldSExtract
- [ ] OpBitFieldUExtract
- [ ] OpBitReverse
- [ ] OpBitCount

</p>
</details>

## Relational & Logical 🛑
<details><summary>Details</summary>
<p>

- [ ] OpAny
- [ ] OpAll
- [ ] OpIsNan
- [ ] OpIsInf
- [ ] OpIsFinite
- [ ] OpIsNormal
- [ ] OpSignBitSet
- [ ] OpLessOrGreater
- [ ] OpOrdered
- [ ] OpUnordered
- [ ] OpLogicalEqual
- [ ] OpLogicalNotEqual
- [ ] OpLogicalOr
- [ ] OpLogicalAnd
- [ ] OpLogicalNot
- [ ] OpSelect
- [ ] OpIEqual
- [ ] OpINotEqual
- [ ] OpUGreaterThan
- [ ] OpSGreaterThan
- [ ] OpUGreaterThanEqual
- [ ] OpSGreaterThanEqual
- [ ] OpULessThan
- [ ] OpSLessThan
- [ ] OpULessThanEqual
- [ ] OpSLessThanEqual
- [ ] OpFOrdEqual
- [ ] OpFUnordEqual
- [ ] OpFOrdNotEqual
- [ ] OpFUnordNotEqual
- [ ] OpFOrdLessThan
- [ ] OpFUnordLessThan
- [ ] OpFOrdGreaterThan
- [ ] OpFUnordGreaterThan
- [ ] OpFOrdLessThanEqual
- [ ] OpFUnordLessThanEqual
- [ ] OpFOrdGreaterThanEqual
- [ ] OpFUnordGreaterThanEqual

</p>
</details>

## Derivative ✅

<details><summary>Details</summary>
<p>

- [x] OpDPdx
- [x] OpDPdy
- [x] OpFwidth
- [x] OpDPdxFine
- [x] OpDPdyFine
- [x] OpFwidthFine
- [x] OpDPdxCoarse
- [x] OpDPdyCoarse
- [x] OpFwidthCoarse

</p>
</details>

## Atomic 🛑

<details><summary>Details</summary>
<p>

- [ ] OpAtomicLoad
- [ ] OpAtomicStore
- [ ] OpAtomicExchange
- [ ] OpAtomicCompareExchange
- [ ] OpAtomicCompareExchangeWeak
- [ ] OpAtomicIIncrement
- [ ] OpAtomicIDecrement
- [ ] OpAtomicIAdd
- [ ] OpAtomicISub
- [ ] OpAtomicSMin
- [ ] OpAtomicUMin
- [ ] OpAtomicSMax
- [ ] OpAtomicUMax
- [ ] OpAtomicAnd
- [ ] OpAtomicOr
- [ ] OpAtomicXor
- [ ] OpAtomicFlagTestAndSet
- [ ] OpAtomicFlagClear
- [ ] OpAtomicFAddEXT

</p>
</details>
