### ISSUE TITLE
Open source repo & project

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#55]
Tracking issue for what we need to do before opening this project now soon! Let's link relevant issues and have checkboxes for them here and drive discussions about it here

What to do before:

- [x] Some real running "hello world" shader
- [x] Go through issues and docs and make sure we don't have anything in it we DON'T want to share 
  - [x] @repi 
  - [x] @arirawr 
- [x] Good enough initial onboarding experience #28
- [x] Include small example Rust shader and screenshot in top of README
- [x] @repi may have thoughts about #48, it'd be nice to have those before opensourcing (and so vaguely public API)
- [x] Draft an announcement post to GH releases.
- [x] Clean up the README: move background/"why embark" sections to post? That would help get the "scope" section more visible, which seems to be a priority.
- [x] Go through README and tweak some language (mention @MaikKlein and RLSL prototype connection more also?) @repi 

CUT for v0.1 release (may do later):
- ~Ideally some Ark shaders #36 (we have a simple similar sky shader instead)~
- ~Sketch out "Compiler Engineer" job ad would be excellent to have posted when we open source the project~

Release checklist:

- [x] Open repo
- [x] Open discord
- [x] Un-draft the release post
- [x] Announce in Discord, link release post
- [x] @repi tweet it out, link release post
- [ ] Add project to [embark.dev](https://embark.dev) and [embark.rs](https://embark.rs) - @arirawr 
- [x] Post on users.rust-lang.org and r/rust - who?

Once released:

- [x] Automerge PRs (#54) @repi
- [x] RLSL update (blog post, link to rust-gpu) @MaikKlein

**Comment by XAMPPRocky** [comment]
Closing as complete :)

**Comment by repi** [comment]
@XAMPPRocky closed it a bit early :) we had some post-release stuff to fix. I added it to https://embark.rs now, but still need to add it to https://embark.dev also, can you do it @XAMPPRocky or otherwise @arirawr ?  

It is pretty easy, just is a data file here https://github.com/embarkStudios/opensource-website
