### ISSUE TITLE
0.4.0 release tracking issue

### ISSUE THREAD

**Issue by oisyn** [EmbarkStudios/rust-gpu#963]
Things that we need to take care of to do a proper `0.4.0` release. By all means edit this post as things come up and change 🙂

## Code changes
- [x] Land SPIR-T prerequisite PRs
- [x] Integrate SPIR-T itself

## Doc changes
- [x] Include past changes in `changelog.md`
- [x] Get proper screenshots
- [x] Do a release write-up
- [x] Go over docs and see whether they're still up to date (I know at least the basic project setup doc isn't)
- [x] Include proper `readme.md` for `crates.io` published crates (also mention things like which nightly each version requires)

## Release checklist
- [x] Publish `spirt` on crates.io
- [x] Use published `spirt` crate in rust-gpu workspace
- [x] Update crate versions to `0.4.0`
- [x] Publish to crates.io

**Comment by eddyb** [comment]
We should do this for older releases (since they're "old news" arguably):
* #930

For the changes going into 0.4.0, I may have went a bit overboard:
* #964
