### ISSUE TITLE
Structured Control Flow

### ISSUE THREAD

**Issue by VZout** [EmbarkStudios/rust-gpu#97]
For non-kernel shaders SPIR-V requires you to mark [structured control flow](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.mobile.html#_a_id_structuredcontrolflow_a_structured_control_flow) with [merge instructions](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.mobile.html#Merge).

Primary Tasks:
* [x] Conditional Branch
* [x] Loops *- in progress*
    * [x] `break` (partially unreachable)
    * [x] `break` (fully unreachable)
    * [x] `continue`
    * [x] `return`
* [x] Switch

Secondary Tasks:
* [ ] Find convergence points using post-dominator tree algorithm instead of my approach. 
* [ ] Optimize loop detection.
* [ ] Reduce duplicate code.

Backlog:
* [ ] "make reducible" pass.
    - The MIR generated from rust is currently reducible. This might change in the future or we might have missed a corner case.

**Comment by Maaarcocr** [comment]
Hey! I know that loops are in progress, but I would be happy to help with them if there was any subtask that you may want to offload to an open source contributor! 

I have some experience with structured control flow, in the past I've worked on a SPMD pass on top of the Julia IR. I'll also be more than happy to work on switch!

**Comment by khyperia** [comment]
Reminder for us: `NO_DCE=1` is broken right now (hangs for a long time - infinitely? - in the structurization pass). We should add `NO_DCE=1` to tests once we fix that.

**Comment by VZout** [comment]
> Hey! I know that loops are in progress, but I would be happy to help with them if there was any subtask that you may want to offload to an open source contributor!
> 
> I have some experience with structured control flow, in the past I've worked on a SPMD pass on top of the Julia IR. I'll also be more than happy to work on switch!

Hey thanks for the offer. I expect to get loops and switches in before the end of the week. But if you want to look into creating a irreducible -> reducible pass that would be very helpful for us in the future. However I believe the plan is to strip the structuration pass and put it into SPIRV-TOOLS once we have the reducible pass since it may be off help to many more people. If you want to talk more in-depth you can always talk to me on the [Embark discord](https://discord.gg/dAuKfZS).
